### ISSUE TITLE
Add extension to Open VSX Registry

### ISSUE THREAD

**Issue by felpau** [probe-rs/vscode#68]
Love your work, and so it would be nice to have this extension available on [Open VSX Registry](https://open-vsx.org/) so that people could access it easily through editors like VSCodium.

**Comment by noppej** [comment]
Thanks for your kind words. We are a small core team, with many other very smart contributors that make a great repo.

That said, we all do this in our spare time, so you will mostly see us build stuff that we need to use ourselves. For instance, I focus on debug capabilities and since I personally use VSCode, I invest a lot of time in this extension and the supporting capabilities in the probe-rs repo.

I don't currently have the cycles to test and release against VSCodium, and invite you to try a PR to confirm it works, and propose changes as necessary (to the extension, the probe-rs api, and/or the CI for publishing to another registry). 

I will leave this enhancement open for you or others to consider :)
